local ffi = require("ffi")

ffi.cdef([[

void* LoadLibraryA(const char*);

void RegisterActiveMods(const char**, int);

void WaitForDotnetInit();

void RegisterEngineAPIFunction(const char*,int);

typedef void (*FOnWorldPostUpdate)();
typedef void (*FOnWorldPreUpdate)();
typedef void (*FOnModPreInit)();
typedef void (*FOnModInit)();
typedef void (*FOnModPostInit)();

typedef struct
{
    FOnWorldPostUpdate OnWorldPostUpdate;
    FOnWorldPreUpdate OnWorldPreUpdate;
    FOnModPreInit OnModPreInit;
    FOnModInit OnModInit;
    FOnModPostInit OnModPostInit;
} Callbacks;

Callbacks GetCallbacks();

]])

-- NoitaNET.NativeLoader
local nativeLoaderDllPath = "mods/NoitaNET/NoitaNET.NativeLoader.dll"

assert(ffi.C.LoadLibraryA(nativeLoaderDllPath) ~= nil)

local lib = ffi.load(nativeLoaderDllPath)

local modIds = ModGetActiveModIDs()
local modCount = #modIds

local modFolders = ffi.new("const char*[?]", modCount, modIds)

lib.RegisterActiveMods(modFolders, modCount)

lib.RegisterEngineAPIFunction("EntityLoad", tonumber(tostring(EntityLoad):sub(11)))
lib.RegisterEngineAPIFunction("EntityLoadEndGameItem", tonumber(tostring(EntityLoadEndGameItem):sub(11)))
lib.RegisterEngineAPIFunction("EntityLoadCameraBound", tonumber(tostring(EntityLoadCameraBound):sub(11)))
lib.RegisterEngineAPIFunction("EntityLoadToEntity", tonumber(tostring(EntityLoadToEntity):sub(11)))
lib.RegisterEngineAPIFunction("EntitySave", tonumber(tostring(EntitySave):sub(11)))
lib.RegisterEngineAPIFunction("EntityCreateNew", tonumber(tostring(EntityCreateNew):sub(11)))
lib.RegisterEngineAPIFunction("EntityKill", tonumber(tostring(EntityKill):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetIsAlive", tonumber(tostring(EntityGetIsAlive):sub(11)))
lib.RegisterEngineAPIFunction("EntityAddComponent", tonumber(tostring(EntityAddComponent):sub(11)))
lib.RegisterEngineAPIFunction("EntityRemoveComponent", tonumber(tostring(EntityRemoveComponent):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetAllComponents", tonumber(tostring(EntityGetAllComponents):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetComponent", tonumber(tostring(EntityGetComponent):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetFirstComponent", tonumber(tostring(EntityGetFirstComponent):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetComponentIncludingDisabled", tonumber(tostring(EntityGetComponentIncludingDisabled):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetFirstComponentIncludingDisabled", tonumber(tostring(EntityGetFirstComponentIncludingDisabled):sub(11)))
lib.RegisterEngineAPIFunction("EntitySetTransform", tonumber(tostring(EntitySetTransform):sub(11)))
lib.RegisterEngineAPIFunction("EntityApplyTransform", tonumber(tostring(EntityApplyTransform):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetTransform", tonumber(tostring(EntityGetTransform):sub(11)))
lib.RegisterEngineAPIFunction("EntityAddChild", tonumber(tostring(EntityAddChild):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetAllChildren", tonumber(tostring(EntityGetAllChildren):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetParent", tonumber(tostring(EntityGetParent):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetRootEntity", tonumber(tostring(EntityGetRootEntity):sub(11)))
lib.RegisterEngineAPIFunction("EntityRemoveFromParent", tonumber(tostring(EntityRemoveFromParent):sub(11)))
lib.RegisterEngineAPIFunction("EntitySetComponentsWithTagEnabled", tonumber(tostring(EntitySetComponentsWithTagEnabled):sub(11)))
lib.RegisterEngineAPIFunction("EntitySetComponentIsEnabled", tonumber(tostring(EntitySetComponentIsEnabled):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetName", tonumber(tostring(EntityGetName):sub(11)))
lib.RegisterEngineAPIFunction("EntitySetName", tonumber(tostring(EntitySetName):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetTags", tonumber(tostring(EntityGetTags):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetWithTag", tonumber(tostring(EntityGetWithTag):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetInRadius", tonumber(tostring(EntityGetInRadius):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetInRadiusWithTag", tonumber(tostring(EntityGetInRadiusWithTag):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetClosest", tonumber(tostring(EntityGetClosest):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetClosestWithTag", tonumber(tostring(EntityGetClosestWithTag):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetWithName", tonumber(tostring(EntityGetWithName):sub(11)))
lib.RegisterEngineAPIFunction("EntityAddTag", tonumber(tostring(EntityAddTag):sub(11)))
lib.RegisterEngineAPIFunction("EntityRemoveTag", tonumber(tostring(EntityRemoveTag):sub(11)))
lib.RegisterEngineAPIFunction("EntityHasTag", tonumber(tostring(EntityHasTag):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetFilename", tonumber(tostring(EntityGetFilename):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetValue", tonumber(tostring(ComponentGetValue):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetValueBool", tonumber(tostring(ComponentGetValueBool):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetValueInt", tonumber(tostring(ComponentGetValueInt):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetValueFloat", tonumber(tostring(ComponentGetValueFloat):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetValueVector2", tonumber(tostring(ComponentGetValueVector2):sub(11)))
lib.RegisterEngineAPIFunction("ComponentSetValue", tonumber(tostring(ComponentSetValue):sub(11)))
lib.RegisterEngineAPIFunction("ComponentSetValueVector2", tonumber(tostring(ComponentSetValueVector2):sub(11)))
lib.RegisterEngineAPIFunction("ComponentSetValueValueRange", tonumber(tostring(ComponentSetValueValueRange):sub(11)))
lib.RegisterEngineAPIFunction("ComponentSetValueValueRangeInt", tonumber(tostring(ComponentSetValueValueRangeInt):sub(11)))
lib.RegisterEngineAPIFunction("ComponentSetMetaCustom", tonumber(tostring(ComponentSetMetaCustom):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetMetaCustom", tonumber(tostring(ComponentGetMetaCustom):sub(11)))
lib.RegisterEngineAPIFunction("ComponentObjectSetValue", tonumber(tostring(ComponentObjectSetValue):sub(11)))
lib.RegisterEngineAPIFunction("ComponentAddTag", tonumber(tostring(ComponentAddTag):sub(11)))
lib.RegisterEngineAPIFunction("ComponentRemoveTag", tonumber(tostring(ComponentRemoveTag):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetTags", tonumber(tostring(ComponentGetTags):sub(11)))
lib.RegisterEngineAPIFunction("ComponentHasTag", tonumber(tostring(ComponentHasTag):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetValue2", tonumber(tostring(ComponentGetValue2):sub(11)))
lib.RegisterEngineAPIFunction("ComponentSetValue2", tonumber(tostring(ComponentSetValue2):sub(11)))
lib.RegisterEngineAPIFunction("ComponentObjectGetValue2", tonumber(tostring(ComponentObjectGetValue2):sub(11)))
lib.RegisterEngineAPIFunction("ComponentObjectSetValue2", tonumber(tostring(ComponentObjectSetValue2):sub(11)))
lib.RegisterEngineAPIFunction("EntityAddComponent2", tonumber(tostring(EntityAddComponent2):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetVectorSize", tonumber(tostring(ComponentGetVectorSize):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetVectorValue", tonumber(tostring(ComponentGetVectorValue):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetVector", tonumber(tostring(ComponentGetVector):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetIsEnabled", tonumber(tostring(ComponentGetIsEnabled):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetMembers", tonumber(tostring(ComponentGetMembers):sub(11)))
lib.RegisterEngineAPIFunction("ComponentObjectGetMembers", tonumber(tostring(ComponentObjectGetMembers):sub(11)))
lib.RegisterEngineAPIFunction("ComponentGetTypeName", tonumber(tostring(ComponentGetTypeName):sub(11)))
lib.RegisterEngineAPIFunction("GetUpdatedEntityID", tonumber(tostring(GetUpdatedEntityID):sub(11)))
lib.RegisterEngineAPIFunction("GetUpdatedComponentID", tonumber(tostring(GetUpdatedComponentID):sub(11)))
lib.RegisterEngineAPIFunction("SetTimeOut", tonumber(tostring(SetTimeOut):sub(11)))
lib.RegisterEngineAPIFunction("RegisterSpawnFunction", tonumber(tostring(RegisterSpawnFunction):sub(11)))
lib.RegisterEngineAPIFunction("SpawnActionItem", tonumber(tostring(SpawnActionItem):sub(11)))
lib.RegisterEngineAPIFunction("SpawnStash", tonumber(tostring(SpawnStash):sub(11)))
lib.RegisterEngineAPIFunction("SpawnApparition", tonumber(tostring(SpawnApparition):sub(11)))
lib.RegisterEngineAPIFunction("LoadEntityToStash", tonumber(tostring(LoadEntityToStash):sub(11)))
lib.RegisterEngineAPIFunction("AddMaterialInventoryMaterial", tonumber(tostring(AddMaterialInventoryMaterial):sub(11)))
lib.RegisterEngineAPIFunction("GetMaterialInventoryMainMaterial", tonumber(tostring(GetMaterialInventoryMainMaterial):sub(11)))
lib.RegisterEngineAPIFunction("GameScreenshake", tonumber(tostring(GameScreenshake):sub(11)))
lib.RegisterEngineAPIFunction("GameOnCompleted", tonumber(tostring(GameOnCompleted):sub(11)))
lib.RegisterEngineAPIFunction("GameGiveAchievement", tonumber(tostring(GameGiveAchievement):sub(11)))
lib.RegisterEngineAPIFunction("GameDoEnding2", tonumber(tostring(GameDoEnding2):sub(11)))
lib.RegisterEngineAPIFunction("GetParallelWorldPosition", tonumber(tostring(GetParallelWorldPosition):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapLoad_KeepPlayer", tonumber(tostring(BiomeMapLoad_KeepPlayer):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapLoad", tonumber(tostring(BiomeMapLoad):sub(11)))
lib.RegisterEngineAPIFunction("BiomeSetValue", tonumber(tostring(BiomeSetValue):sub(11)))
lib.RegisterEngineAPIFunction("BiomeGetValue", tonumber(tostring(BiomeGetValue):sub(11)))
lib.RegisterEngineAPIFunction("BiomeObjectSetValue", tonumber(tostring(BiomeObjectSetValue):sub(11)))
lib.RegisterEngineAPIFunction("BiomeVegetationSetValue", tonumber(tostring(BiomeVegetationSetValue):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMaterialSetValue", tonumber(tostring(BiomeMaterialSetValue):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMaterialGetValue", tonumber(tostring(BiomeMaterialGetValue):sub(11)))
lib.RegisterEngineAPIFunction("GameIsIntroPlaying", tonumber(tostring(GameIsIntroPlaying):sub(11)))
lib.RegisterEngineAPIFunction("GameGetIsGamepadConnected", tonumber(tostring(GameGetIsGamepadConnected):sub(11)))
lib.RegisterEngineAPIFunction("GameGetWorldStateEntity", tonumber(tostring(GameGetWorldStateEntity):sub(11)))
lib.RegisterEngineAPIFunction("GameGetPlayerStatsEntity", tonumber(tostring(GameGetPlayerStatsEntity):sub(11)))
lib.RegisterEngineAPIFunction("GameGetOrbCountAllTime", tonumber(tostring(GameGetOrbCountAllTime):sub(11)))
lib.RegisterEngineAPIFunction("GameGetOrbCountThisRun", tonumber(tostring(GameGetOrbCountThisRun):sub(11)))
lib.RegisterEngineAPIFunction("GameGetOrbCollectedThisRun", tonumber(tostring(GameGetOrbCollectedThisRun):sub(11)))
lib.RegisterEngineAPIFunction("GameGetOrbCollectedAllTime", tonumber(tostring(GameGetOrbCollectedAllTime):sub(11)))
lib.RegisterEngineAPIFunction("GameClearOrbsFoundThisRun", tonumber(tostring(GameClearOrbsFoundThisRun):sub(11)))
lib.RegisterEngineAPIFunction("GameGetOrbCountTotal", tonumber(tostring(GameGetOrbCountTotal):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetName", tonumber(tostring(CellFactory_GetName):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetType", tonumber(tostring(CellFactory_GetType):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetUIName", tonumber(tostring(CellFactory_GetUIName):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetAllLiquids", tonumber(tostring(CellFactory_GetAllLiquids):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetAllSands", tonumber(tostring(CellFactory_GetAllSands):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetAllGases", tonumber(tostring(CellFactory_GetAllGases):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetAllFires", tonumber(tostring(CellFactory_GetAllFires):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetAllSolids", tonumber(tostring(CellFactory_GetAllSolids):sub(11)))
lib.RegisterEngineAPIFunction("CellFactory_GetTags", tonumber(tostring(CellFactory_GetTags):sub(11)))
lib.RegisterEngineAPIFunction("GameGetCameraPos", tonumber(tostring(GameGetCameraPos):sub(11)))
lib.RegisterEngineAPIFunction("GameSetCameraPos", tonumber(tostring(GameSetCameraPos):sub(11)))
lib.RegisterEngineAPIFunction("GameSetCameraFree", tonumber(tostring(GameSetCameraFree):sub(11)))
lib.RegisterEngineAPIFunction("GameGetCameraBounds", tonumber(tostring(GameGetCameraBounds):sub(11)))
lib.RegisterEngineAPIFunction("GameRegenItemAction", tonumber(tostring(GameRegenItemAction):sub(11)))
lib.RegisterEngineAPIFunction("GameRegenItemActionsInContainer", tonumber(tostring(GameRegenItemActionsInContainer):sub(11)))
lib.RegisterEngineAPIFunction("GameRegenItemActionsInPlayer", tonumber(tostring(GameRegenItemActionsInPlayer):sub(11)))
lib.RegisterEngineAPIFunction("GameKillInventoryItem", tonumber(tostring(GameKillInventoryItem):sub(11)))
lib.RegisterEngineAPIFunction("GamePickUpInventoryItem", tonumber(tostring(GamePickUpInventoryItem):sub(11)))
lib.RegisterEngineAPIFunction("GameGetAllInventoryItems", tonumber(tostring(GameGetAllInventoryItems):sub(11)))
lib.RegisterEngineAPIFunction("GameDropAllItems", tonumber(tostring(GameDropAllItems):sub(11)))
lib.RegisterEngineAPIFunction("GameDropPlayerInventoryItems", tonumber(tostring(GameDropPlayerInventoryItems):sub(11)))
lib.RegisterEngineAPIFunction("GameDestroyInventoryItems", tonumber(tostring(GameDestroyInventoryItems):sub(11)))
lib.RegisterEngineAPIFunction("GameIsInventoryOpen", tonumber(tostring(GameIsInventoryOpen):sub(11)))
lib.RegisterEngineAPIFunction("GameTriggerGameOver", tonumber(tostring(GameTriggerGameOver):sub(11)))
lib.RegisterEngineAPIFunction("LoadPixelScene", tonumber(tostring(LoadPixelScene):sub(11)))
lib.RegisterEngineAPIFunction("LoadBackgroundSprite", tonumber(tostring(LoadBackgroundSprite):sub(11)))
lib.RegisterEngineAPIFunction("GameCreateCosmeticParticle", tonumber(tostring(GameCreateCosmeticParticle):sub(11)))
lib.RegisterEngineAPIFunction("GameCreateParticle", tonumber(tostring(GameCreateParticle):sub(11)))
lib.RegisterEngineAPIFunction("GameCreateSpriteForXFrames", tonumber(tostring(GameCreateSpriteForXFrames):sub(11)))
lib.RegisterEngineAPIFunction("GameShootProjectile", tonumber(tostring(GameShootProjectile):sub(11)))
lib.RegisterEngineAPIFunction("EntityInflictDamage", tonumber(tostring(EntityInflictDamage):sub(11)))
lib.RegisterEngineAPIFunction("EntityIngestMaterial", tonumber(tostring(EntityIngestMaterial):sub(11)))
lib.RegisterEngineAPIFunction("EntityRemoveIngestionStatusEffect", tonumber(tostring(EntityRemoveIngestionStatusEffect):sub(11)))
lib.RegisterEngineAPIFunction("EntityAddRandomStains", tonumber(tostring(EntityAddRandomStains):sub(11)))
lib.RegisterEngineAPIFunction("EntitySetDamageFromMaterial", tonumber(tostring(EntitySetDamageFromMaterial):sub(11)))
lib.RegisterEngineAPIFunction("EntityRefreshSprite", tonumber(tostring(EntityRefreshSprite):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetWandCapacity", tonumber(tostring(EntityGetWandCapacity):sub(11)))
lib.RegisterEngineAPIFunction("GamePlayAnimation", tonumber(tostring(GamePlayAnimation):sub(11)))
lib.RegisterEngineAPIFunction("GameGetVelocityCompVelocity", tonumber(tostring(GameGetVelocityCompVelocity):sub(11)))
lib.RegisterEngineAPIFunction("GameGetGameEffect", tonumber(tostring(GameGetGameEffect):sub(11)))
lib.RegisterEngineAPIFunction("GameGetGameEffectCount", tonumber(tostring(GameGetGameEffectCount):sub(11)))
lib.RegisterEngineAPIFunction("LoadGameEffectEntityTo", tonumber(tostring(LoadGameEffectEntityTo):sub(11)))
lib.RegisterEngineAPIFunction("GetGameEffectLoadTo", tonumber(tostring(GetGameEffectLoadTo):sub(11)))
lib.RegisterEngineAPIFunction("PolymorphTableAddEntity", tonumber(tostring(PolymorphTableAddEntity):sub(11)))
lib.RegisterEngineAPIFunction("PolymorphTableRemoveEntity", tonumber(tostring(PolymorphTableRemoveEntity):sub(11)))
lib.RegisterEngineAPIFunction("PolymorphTableGet", tonumber(tostring(PolymorphTableGet):sub(11)))
lib.RegisterEngineAPIFunction("PolymorphTableSet", tonumber(tostring(PolymorphTableSet):sub(11)))
lib.RegisterEngineAPIFunction("SetPlayerSpawnLocation", tonumber(tostring(SetPlayerSpawnLocation):sub(11)))
lib.RegisterEngineAPIFunction("UnlockItem", tonumber(tostring(UnlockItem):sub(11)))
lib.RegisterEngineAPIFunction("GameGetPotionColorUint", tonumber(tostring(GameGetPotionColorUint):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetFirstHitboxCenter", tonumber(tostring(EntityGetFirstHitboxCenter):sub(11)))
lib.RegisterEngineAPIFunction("Raytrace", tonumber(tostring(Raytrace):sub(11)))
lib.RegisterEngineAPIFunction("RaytraceSurfaces", tonumber(tostring(RaytraceSurfaces):sub(11)))
lib.RegisterEngineAPIFunction("RaytraceSurfacesAndLiquiform", tonumber(tostring(RaytraceSurfacesAndLiquiform):sub(11)))
lib.RegisterEngineAPIFunction("RaytracePlatforms", tonumber(tostring(RaytracePlatforms):sub(11)))
lib.RegisterEngineAPIFunction("FindFreePositionForBody", tonumber(tostring(FindFreePositionForBody):sub(11)))
lib.RegisterEngineAPIFunction("GetSurfaceNormal", tonumber(tostring(GetSurfaceNormal):sub(11)))
lib.RegisterEngineAPIFunction("DoesWorldExistAt", tonumber(tostring(DoesWorldExistAt):sub(11)))
lib.RegisterEngineAPIFunction("StringToHerdId", tonumber(tostring(StringToHerdId):sub(11)))
lib.RegisterEngineAPIFunction("HerdIdToString", tonumber(tostring(HerdIdToString):sub(11)))
lib.RegisterEngineAPIFunction("GetHerdRelation", tonumber(tostring(GetHerdRelation):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetHerdRelation", tonumber(tostring(EntityGetHerdRelation):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetHerdRelationSafe", tonumber(tostring(EntityGetHerdRelationSafe):sub(11)))
lib.RegisterEngineAPIFunction("GenomeSetHerdId", tonumber(tostring(GenomeSetHerdId):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetClosestWormAttractor", tonumber(tostring(EntityGetClosestWormAttractor):sub(11)))
lib.RegisterEngineAPIFunction("EntityGetClosestWormDetractor", tonumber(tostring(EntityGetClosestWormDetractor):sub(11)))
lib.RegisterEngineAPIFunction("GamePrint", tonumber(tostring(GamePrint):sub(11)))
lib.RegisterEngineAPIFunction("GamePrintImportant", tonumber(tostring(GamePrintImportant):sub(11)))
lib.RegisterEngineAPIFunction("DEBUG_GetMouseWorld", tonumber(tostring(DEBUG_GetMouseWorld):sub(11)))
lib.RegisterEngineAPIFunction("DEBUG_MARK", tonumber(tostring(DEBUG_MARK):sub(11)))
lib.RegisterEngineAPIFunction("GameGetFrameNum", tonumber(tostring(GameGetFrameNum):sub(11)))
lib.RegisterEngineAPIFunction("GameGetRealWorldTimeSinceStarted", tonumber(tostring(GameGetRealWorldTimeSinceStarted):sub(11)))
lib.RegisterEngineAPIFunction("InputIsKeyDown", tonumber(tostring(InputIsKeyDown):sub(11)))
lib.RegisterEngineAPIFunction("InputIsKeyJustDown", tonumber(tostring(InputIsKeyJustDown):sub(11)))
lib.RegisterEngineAPIFunction("InputIsKeyJustUp", tonumber(tostring(InputIsKeyJustUp):sub(11)))
lib.RegisterEngineAPIFunction("InputGetMousePosOnScreen", tonumber(tostring(InputGetMousePosOnScreen):sub(11)))
lib.RegisterEngineAPIFunction("InputIsMouseButtonDown", tonumber(tostring(InputIsMouseButtonDown):sub(11)))
lib.RegisterEngineAPIFunction("InputIsMouseButtonJustDown", tonumber(tostring(InputIsMouseButtonJustDown):sub(11)))
lib.RegisterEngineAPIFunction("InputIsMouseButtonJustUp", tonumber(tostring(InputIsMouseButtonJustUp):sub(11)))
lib.RegisterEngineAPIFunction("IsPlayer", tonumber(tostring(IsPlayer):sub(11)))
lib.RegisterEngineAPIFunction("IsInvisible", tonumber(tostring(IsInvisible):sub(11)))
lib.RegisterEngineAPIFunction("GameIsDailyRun", tonumber(tostring(GameIsDailyRun):sub(11)))
lib.RegisterEngineAPIFunction("GameIsDailyRunOrDailyPracticeRun", tonumber(tostring(GameIsDailyRunOrDailyPracticeRun):sub(11)))
lib.RegisterEngineAPIFunction("GameIsModeFullyDeterministic", tonumber(tostring(GameIsModeFullyDeterministic):sub(11)))
lib.RegisterEngineAPIFunction("GlobalsSetValue", tonumber(tostring(GlobalsSetValue):sub(11)))
lib.RegisterEngineAPIFunction("GlobalsGetValue", tonumber(tostring(GlobalsGetValue):sub(11)))
lib.RegisterEngineAPIFunction("MagicNumbersGetValue", tonumber(tostring(MagicNumbersGetValue):sub(11)))
lib.RegisterEngineAPIFunction("SetWorldSeed", tonumber(tostring(SetWorldSeed):sub(11)))
lib.RegisterEngineAPIFunction("SessionNumbersGetValue", tonumber(tostring(SessionNumbersGetValue):sub(11)))
lib.RegisterEngineAPIFunction("SessionNumbersSetValue", tonumber(tostring(SessionNumbersSetValue):sub(11)))
lib.RegisterEngineAPIFunction("SessionNumbersSave", tonumber(tostring(SessionNumbersSave):sub(11)))
lib.RegisterEngineAPIFunction("AutosaveDisable", tonumber(tostring(AutosaveDisable):sub(11)))
lib.RegisterEngineAPIFunction("StatsGetValue", tonumber(tostring(StatsGetValue):sub(11)))
lib.RegisterEngineAPIFunction("StatsGlobalGetValue", tonumber(tostring(StatsGlobalGetValue):sub(11)))
lib.RegisterEngineAPIFunction("StatsBiomeGetValue", tonumber(tostring(StatsBiomeGetValue):sub(11)))
lib.RegisterEngineAPIFunction("StatsBiomeReset", tonumber(tostring(StatsBiomeReset):sub(11)))
lib.RegisterEngineAPIFunction("StatsLogPlayerKill", tonumber(tostring(StatsLogPlayerKill):sub(11)))
lib.RegisterEngineAPIFunction("CreateItemActionEntity", tonumber(tostring(CreateItemActionEntity):sub(11)))
lib.RegisterEngineAPIFunction("GetRandomActionWithType", tonumber(tostring(GetRandomActionWithType):sub(11)))
lib.RegisterEngineAPIFunction("GetRandomAction", tonumber(tostring(GetRandomAction):sub(11)))
lib.RegisterEngineAPIFunction("GameGetDateAndTimeUTC", tonumber(tostring(GameGetDateAndTimeUTC):sub(11)))
lib.RegisterEngineAPIFunction("GameGetDateAndTimeLocal", tonumber(tostring(GameGetDateAndTimeLocal):sub(11)))
lib.RegisterEngineAPIFunction("GameEmitRainParticles", tonumber(tostring(GameEmitRainParticles):sub(11)))
lib.RegisterEngineAPIFunction("GameCutThroughWorldVertical", tonumber(tostring(GameCutThroughWorldVertical):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapSetSize", tonumber(tostring(BiomeMapSetSize):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapGetSize", tonumber(tostring(BiomeMapGetSize):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapSetPixel", tonumber(tostring(BiomeMapSetPixel):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapGetPixel", tonumber(tostring(BiomeMapGetPixel):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapConvertPixelFromUintToInt", tonumber(tostring(BiomeMapConvertPixelFromUintToInt):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapLoadImage", tonumber(tostring(BiomeMapLoadImage):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapLoadImageCropped", tonumber(tostring(BiomeMapLoadImageCropped):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapGetVerticalPositionInsideBiome", tonumber(tostring(BiomeMapGetVerticalPositionInsideBiome):sub(11)))
lib.RegisterEngineAPIFunction("BiomeMapGetName", tonumber(tostring(BiomeMapGetName):sub(11)))
lib.RegisterEngineAPIFunction("SetRandomSeed", tonumber(tostring(SetRandomSeed):sub(11)))
lib.RegisterEngineAPIFunction("Random", tonumber(tostring(Random):sub(11)))
lib.RegisterEngineAPIFunction("Randomf", tonumber(tostring(Randomf):sub(11)))
lib.RegisterEngineAPIFunction("RandomDistribution", tonumber(tostring(RandomDistribution):sub(11)))
lib.RegisterEngineAPIFunction("RandomDistributionf", tonumber(tostring(RandomDistributionf):sub(11)))
lib.RegisterEngineAPIFunction("ProceduralRandom", tonumber(tostring(ProceduralRandom):sub(11)))
lib.RegisterEngineAPIFunction("ProceduralRandomf", tonumber(tostring(ProceduralRandomf):sub(11)))
lib.RegisterEngineAPIFunction("ProceduralRandomi", tonumber(tostring(ProceduralRandomi):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsAddBodyImage", tonumber(tostring(PhysicsAddBodyImage):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsAddBodyCreateBox", tonumber(tostring(PhysicsAddBodyCreateBox):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsAddJoint", tonumber(tostring(PhysicsAddJoint):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsApplyForce", tonumber(tostring(PhysicsApplyForce):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsApplyTorque", tonumber(tostring(PhysicsApplyTorque):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsApplyTorqueToComponent", tonumber(tostring(PhysicsApplyTorqueToComponent):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsApplyForceOnArea", tonumber(tostring(PhysicsApplyForceOnArea):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsRemoveJoints", tonumber(tostring(PhysicsRemoveJoints):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsSetStatic", tonumber(tostring(PhysicsSetStatic):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsGetComponentVelocity", tonumber(tostring(PhysicsGetComponentVelocity):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsGetComponentAngularVelocity", tonumber(tostring(PhysicsGetComponentAngularVelocity):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsBody2InitFromComponents", tonumber(tostring(PhysicsBody2InitFromComponents):sub(11)))
lib.RegisterEngineAPIFunction("PhysicsVecToGameVec", tonumber(tostring(PhysicsVecToGameVec):sub(11)))
lib.RegisterEngineAPIFunction("GameVecToPhysicsVec", tonumber(tostring(GameVecToPhysicsVec):sub(11)))
lib.RegisterEngineAPIFunction("LooseChunk", tonumber(tostring(LooseChunk):sub(11)))
lib.RegisterEngineAPIFunction("AddFlagPersistent", tonumber(tostring(AddFlagPersistent):sub(11)))
lib.RegisterEngineAPIFunction("RemoveFlagPersistent", tonumber(tostring(RemoveFlagPersistent):sub(11)))
lib.RegisterEngineAPIFunction("HasFlagPersistent", tonumber(tostring(HasFlagPersistent):sub(11)))
lib.RegisterEngineAPIFunction("GameAddFlagRun", tonumber(tostring(GameAddFlagRun):sub(11)))
lib.RegisterEngineAPIFunction("GameRemoveFlagRun", tonumber(tostring(GameRemoveFlagRun):sub(11)))
lib.RegisterEngineAPIFunction("GameHasFlagRun", tonumber(tostring(GameHasFlagRun):sub(11)))
lib.RegisterEngineAPIFunction("GameTriggerMusicEvent", tonumber(tostring(GameTriggerMusicEvent):sub(11)))
lib.RegisterEngineAPIFunction("GameTriggerMusicCue", tonumber(tostring(GameTriggerMusicCue):sub(11)))
lib.RegisterEngineAPIFunction("GameTriggerMusicFadeOutAndDequeueAll", tonumber(tostring(GameTriggerMusicFadeOutAndDequeueAll):sub(11)))
lib.RegisterEngineAPIFunction("GamePlaySound", tonumber(tostring(GamePlaySound):sub(11)))
lib.RegisterEngineAPIFunction("GameEntityPlaySound", tonumber(tostring(GameEntityPlaySound):sub(11)))
lib.RegisterEngineAPIFunction("GameEntityPlaySoundLoop", tonumber(tostring(GameEntityPlaySoundLoop):sub(11)))
lib.RegisterEngineAPIFunction("GameSetPostFxParameter", tonumber(tostring(GameSetPostFxParameter):sub(11)))
lib.RegisterEngineAPIFunction("GameUnsetPostFxParameter", tonumber(tostring(GameUnsetPostFxParameter):sub(11)))
lib.RegisterEngineAPIFunction("GameTextGetTranslatedOrNot", tonumber(tostring(GameTextGetTranslatedOrNot):sub(11)))
lib.RegisterEngineAPIFunction("GameTextGet", tonumber(tostring(GameTextGet):sub(11)))
lib.RegisterEngineAPIFunction("GuiCreate", tonumber(tostring(GuiCreate):sub(11)))
lib.RegisterEngineAPIFunction("GuiDestroy", tonumber(tostring(GuiDestroy):sub(11)))
lib.RegisterEngineAPIFunction("GuiStartFrame", tonumber(tostring(GuiStartFrame):sub(11)))
lib.RegisterEngineAPIFunction("GuiOptionsAdd", tonumber(tostring(GuiOptionsAdd):sub(11)))
lib.RegisterEngineAPIFunction("GuiOptionsRemove", tonumber(tostring(GuiOptionsRemove):sub(11)))
lib.RegisterEngineAPIFunction("GuiOptionsClear", tonumber(tostring(GuiOptionsClear):sub(11)))
lib.RegisterEngineAPIFunction("GuiOptionsAddForNextWidget", tonumber(tostring(GuiOptionsAddForNextWidget):sub(11)))
lib.RegisterEngineAPIFunction("GuiColorSetForNextWidget", tonumber(tostring(GuiColorSetForNextWidget):sub(11)))
lib.RegisterEngineAPIFunction("GuiZSet", tonumber(tostring(GuiZSet):sub(11)))
lib.RegisterEngineAPIFunction("GuiZSetForNextWidget", tonumber(tostring(GuiZSetForNextWidget):sub(11)))
lib.RegisterEngineAPIFunction("GuiIdPush", tonumber(tostring(GuiIdPush):sub(11)))
lib.RegisterEngineAPIFunction("GuiIdPushString", tonumber(tostring(GuiIdPushString):sub(11)))
lib.RegisterEngineAPIFunction("GuiIdPop", tonumber(tostring(GuiIdPop):sub(11)))
lib.RegisterEngineAPIFunction("GuiAnimateBegin", tonumber(tostring(GuiAnimateBegin):sub(11)))
lib.RegisterEngineAPIFunction("GuiAnimateEnd", tonumber(tostring(GuiAnimateEnd):sub(11)))
lib.RegisterEngineAPIFunction("GuiAnimateAlphaFadeIn", tonumber(tostring(GuiAnimateAlphaFadeIn):sub(11)))
lib.RegisterEngineAPIFunction("GuiAnimateScaleIn", tonumber(tostring(GuiAnimateScaleIn):sub(11)))
lib.RegisterEngineAPIFunction("GuiText", tonumber(tostring(GuiText):sub(11)))
lib.RegisterEngineAPIFunction("GuiTextCentered", tonumber(tostring(GuiTextCentered):sub(11)))
lib.RegisterEngineAPIFunction("GuiImage", tonumber(tostring(GuiImage):sub(11)))
lib.RegisterEngineAPIFunction("GuiImageNinePiece", tonumber(tostring(GuiImageNinePiece):sub(11)))
lib.RegisterEngineAPIFunction("GuiButton", tonumber(tostring(GuiButton):sub(11)))
lib.RegisterEngineAPIFunction("GuiImageButton", tonumber(tostring(GuiImageButton):sub(11)))
lib.RegisterEngineAPIFunction("GuiSlider", tonumber(tostring(GuiSlider):sub(11)))
lib.RegisterEngineAPIFunction("GuiTextInput", tonumber(tostring(GuiTextInput):sub(11)))
lib.RegisterEngineAPIFunction("GuiBeginAutoBox", tonumber(tostring(GuiBeginAutoBox):sub(11)))
lib.RegisterEngineAPIFunction("GuiEndAutoBoxNinePiece", tonumber(tostring(GuiEndAutoBoxNinePiece):sub(11)))
lib.RegisterEngineAPIFunction("GuiTooltip", tonumber(tostring(GuiTooltip):sub(11)))
lib.RegisterEngineAPIFunction("GuiBeginScrollContainer", tonumber(tostring(GuiBeginScrollContainer):sub(11)))
lib.RegisterEngineAPIFunction("GuiEndScrollContainer", tonumber(tostring(GuiEndScrollContainer):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutBeginHorizontal", tonumber(tostring(GuiLayoutBeginHorizontal):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutBeginVertical", tonumber(tostring(GuiLayoutBeginVertical):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutAddHorizontalSpacing", tonumber(tostring(GuiLayoutAddHorizontalSpacing):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutAddVerticalSpacing", tonumber(tostring(GuiLayoutAddVerticalSpacing):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutEnd", tonumber(tostring(GuiLayoutEnd):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutBeginLayer", tonumber(tostring(GuiLayoutBeginLayer):sub(11)))
lib.RegisterEngineAPIFunction("GuiLayoutEndLayer", tonumber(tostring(GuiLayoutEndLayer):sub(11)))
lib.RegisterEngineAPIFunction("GuiGetScreenDimensions", tonumber(tostring(GuiGetScreenDimensions):sub(11)))
lib.RegisterEngineAPIFunction("GuiGetTextDimensions", tonumber(tostring(GuiGetTextDimensions):sub(11)))
lib.RegisterEngineAPIFunction("GuiGetImageDimensions", tonumber(tostring(GuiGetImageDimensions):sub(11)))
lib.RegisterEngineAPIFunction("GuiGetPreviousWidgetInfo", tonumber(tostring(GuiGetPreviousWidgetInfo):sub(11)))
lib.RegisterEngineAPIFunction("GameIsBetaBuild", tonumber(tostring(GameIsBetaBuild):sub(11)))
lib.RegisterEngineAPIFunction("DebugGetIsDevBuild", tonumber(tostring(DebugGetIsDevBuild):sub(11)))
lib.RegisterEngineAPIFunction("DebugEnableTrailerMode", tonumber(tostring(DebugEnableTrailerMode):sub(11)))
lib.RegisterEngineAPIFunction("GameGetIsTrailerModeEnabled", tonumber(tostring(GameGetIsTrailerModeEnabled):sub(11)))
lib.RegisterEngineAPIFunction("Debug_SaveTestPlayer", tonumber(tostring(Debug_SaveTestPlayer):sub(11)))
lib.RegisterEngineAPIFunction("DebugBiomeMapGetFilename", tonumber(tostring(DebugBiomeMapGetFilename):sub(11)))
lib.RegisterEngineAPIFunction("EntityConvertToMaterial", tonumber(tostring(EntityConvertToMaterial):sub(11)))
lib.RegisterEngineAPIFunction("ConvertEverythingToGold", tonumber(tostring(ConvertEverythingToGold):sub(11)))
lib.RegisterEngineAPIFunction("ConvertMaterialEverywhere", tonumber(tostring(ConvertMaterialEverywhere):sub(11)))
lib.RegisterEngineAPIFunction("ConvertMaterialOnAreaInstantly", tonumber(tostring(ConvertMaterialOnAreaInstantly):sub(11)))
lib.RegisterEngineAPIFunction("LoadRagdoll", tonumber(tostring(LoadRagdoll):sub(11)))
lib.RegisterEngineAPIFunction("GetDailyPracticeRunSeed", tonumber(tostring(GetDailyPracticeRunSeed):sub(11)))
lib.RegisterEngineAPIFunction("ModIsEnabled", tonumber(tostring(ModIsEnabled):sub(11)))
lib.RegisterEngineAPIFunction("ModGetActiveModIDs", tonumber(tostring(ModGetActiveModIDs):sub(11)))
lib.RegisterEngineAPIFunction("ModGetAPIVersion", tonumber(tostring(ModGetAPIVersion):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingGet", tonumber(tostring(ModSettingGet):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingSet", tonumber(tostring(ModSettingSet):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingGetNextValue", tonumber(tostring(ModSettingGetNextValue):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingSetNextValue", tonumber(tostring(ModSettingSetNextValue):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingRemove", tonumber(tostring(ModSettingRemove):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingGetCount", tonumber(tostring(ModSettingGetCount):sub(11)))
lib.RegisterEngineAPIFunction("ModSettingGetAtIndex", tonumber(tostring(ModSettingGetAtIndex):sub(11)))
lib.RegisterEngineAPIFunction("StreamingGetIsConnected", tonumber(tostring(StreamingGetIsConnected):sub(11)))
lib.RegisterEngineAPIFunction("StreamingGetConnectedChannelName", tonumber(tostring(StreamingGetConnectedChannelName):sub(11)))
lib.RegisterEngineAPIFunction("StreamingGetVotingCycleDurationFrames", tonumber(tostring(StreamingGetVotingCycleDurationFrames):sub(11)))
lib.RegisterEngineAPIFunction("StreamingGetRandomViewerName", tonumber(tostring(StreamingGetRandomViewerName):sub(11)))
lib.RegisterEngineAPIFunction("StreamingSetCustomPhaseDurations", tonumber(tostring(StreamingSetCustomPhaseDurations):sub(11)))
lib.RegisterEngineAPIFunction("StreamingForceNewVoting", tonumber(tostring(StreamingForceNewVoting):sub(11)))
lib.RegisterEngineAPIFunction("StreamingSetVotingEnabled", tonumber(tostring(StreamingSetVotingEnabled):sub(11)))
lib.RegisterEngineAPIFunction("ModLuaFileAppend", tonumber(tostring(ModLuaFileAppend):sub(11)))
lib.RegisterEngineAPIFunction("ModTextFileGetContent", tonumber(tostring(ModTextFileGetContent):sub(11)))
lib.RegisterEngineAPIFunction("ModTextFileSetContent", tonumber(tostring(ModTextFileSetContent):sub(11)))
lib.RegisterEngineAPIFunction("ModTextFileWhoSetContent", tonumber(tostring(ModTextFileWhoSetContent):sub(11)))
lib.RegisterEngineAPIFunction("ModMagicNumbersFileAdd", tonumber(tostring(ModMagicNumbersFileAdd):sub(11)))
lib.RegisterEngineAPIFunction("ModMaterialsFileAdd", tonumber(tostring(ModMaterialsFileAdd):sub(11)))
lib.RegisterEngineAPIFunction("ModRegisterAudioEventMappings", tonumber(tostring(ModRegisterAudioEventMappings):sub(11)))
lib.RegisterEngineAPIFunction("ModDevGenerateSpriteUVsForDirectory", tonumber(tostring(ModDevGenerateSpriteUVsForDirectory):sub(11)))
lib.RegisterEngineAPIFunction("SetValueNumber", tonumber(tostring(SetValueNumber):sub(11)))
lib.RegisterEngineAPIFunction("GetValueNumber", tonumber(tostring(GetValueNumber):sub(11)))
lib.RegisterEngineAPIFunction("SetValueInteger", tonumber(tostring(SetValueInteger):sub(11)))
lib.RegisterEngineAPIFunction("GetValueInteger", tonumber(tostring(GetValueInteger):sub(11)))
lib.RegisterEngineAPIFunction("SetValueBool", tonumber(tostring(SetValueBool):sub(11)))
lib.RegisterEngineAPIFunction("GetValueBool", tonumber(tostring(GetValueBool):sub(11)))

lib.WaitForDotnetInit()

local callbackTable = lib.GetCallbacks()

function OnWorldPostUpdate()
    callbackTable.OnWorldPostUpdate()
end

function OnWorldPreUpdate()
    callbackTable.OnWorldPreUpdate()
end

function OnModPreInit()
    callbackTable.OnModPreInit();
end

function OnModInit()
    callbackTable.OnModInit();
end

function OnModPostInit()
    callbackTable.OnModPostInit();
end
